name: Test dbForge Module on Self-hosted Runner

on:
  workflow_dispatch:

jobs:
  test-dbforge-module:
    runs-on: self-hosted
    steps:
      - name: Verify runner and PowerShell
        run: |
          $PSVersionTable
        shell: powershell

      - name: Load dbForge Module and List Cmdlets
        run: |
          Import-Module "C:\Program Files\Devart\dbForge DevOps Automation PowerShell for SQL Server\dbforge.sqlautomation.powershell.dll"
          
          Write-Host "`n✅ dbForge Module Loaded Successfully"
          
          # List all dbForge cmdlets to verify it's working
          Get-Command -Module dbForge.SqlAutomation.PowerShell | Format-Table Name, CommandType
        shell: powershell
