name: Test dbForge Module on Self-hosted Runner

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: powershell

jobs:
  test-dbforge-module:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify PowerShell Environment
        run: |
          $PSVersionTable

      - name: Load dbForge Module and List Commands
        run: |
          Import-Module "C:\Program Files\Devart\dbForge DevOps Automation PowerShell for SQL Server\dbforge.sqlautomation.powershell.dll"

          Write-Host "`n✅ dbForge Module Loaded Successfully"

          # Show all available dbForge cmdlets
          Get-Command -Module dbForge.SqlAutomation.PowerShell | Format-Table Name, CommandType
