name: Test dbForge Module on Self-hosted Runner

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: powershell

jobs:
  test-dbforge-module:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Load dbForge Module and List Commands
        run: |
          Import-Module Devart.DbForge.DevOpsAutomation.SqlServer -ErrorAction Stop

          Write-Host "`n✅ dbForge Module Loaded Successfully"

          # Show all available dbForge cmdlets
          Get-Command -Module Devart.DbForge.DevOpsAutomation.SqlServer | Format-Table Name, CommandType

